---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cryogenics/bbl-deployment
    tag: 8.4.x

inputs:
- name: bbl-ci
- name: bbl-states

outputs:
- name: concourse-vars

params:
  BBL_STATE_DIR:

run:
  path: bbl-ci/ci/tasks/get-concourse-test-vars/task
