---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cryogenics/bbl-deployment
    tag: 8.4.x

inputs:
- name: bb-ci
- name: bbl-release
- name: homebrew-tap

outputs:
- name: updated-brew-tap

run:
  path: bbl-ci/ci/tasks/bump-brew-tap/task
